---

- name: Firewalld | Start and Enale service
  systemd:
    name: firewalld
    state: started
    enabled: yes
    daemon_reload: yes
    force: yes

# sudo firewall-cmd --zone="internal" --change-interface=eth0
- name: Firewalld | Change zone interface
  ansible.posix.firewalld:
    zone: "{{ default_zone }}"
    interface: "{{ networks.ethernet_name }}"
    permanent: yes
    state: enabled
    immediate: yes

# TODO cuando el modulo tenga la funcionalidad, hay que refactorizar
# el permanent va implicito con este comando
# sudo firewall-cmd --set-default-zone="internat"
- name: Firewalld | Set default zone
  shell: "firewall-cmd --set-default-zone={{ default_zone }}"

#  sudo firewall-cmd --zone="$ZONE" --add-service=http
#  sudo firewall-cmd --zone="$ZONE" --add-service=https
#  sudo firewall-cmd --zone="$ZONE" --add-service=ssh
- name: Firewalld | Enabled services
  ansible.posix.firewalld:
    zone: "{{ default_zone }}"
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - http
    - ssh
    - dns

- name: Firewalld | Disabled services
  ansible.posix.firewalld:
    zone: "{{ default_zone }}"
    service: "{{ item }}"
    state: disabled
    permanent: yes
    immediate: yes
  loop:
    - dhcpv6-client
    - mdns
    - samba-client

- name: Firewalld | reload
  shell: firewall-cmd --reload

- name: Firewalld | Get info
  block:
    - name: Firewalld | Get info get-default-zone
      shell: firewall-cmd --get-default-zone
      register: _firewalld_defaut_zone
      changed_when: false

    - name: Firewalld | Get info get-active-zones
      shell: firewall-cmd --get-active-zones
      register: _firewalld_active_zone
      changed_when: false

    - name: Firewalld | Get info zone --list-all
      shell: firewall-cmd --zone="{{ default_zone }}" --list-all
      register: _firewalld_zone_info
      changed_when: false

    - name: Firewalld | Get Default Zone
      debug: var=_firewalld_defaut_zone.stdout_lines

    - name: Firewalld | Get Active Zones
      debug: var=_firewalld_active_zone.stdout_lines

    - name: Firewalld | Get Config zone
      debug: var=_firewalld_zone_info.stdout_lines

